### ISSUE TITLE
KeyError: 'videoDetails'

### ISSUE THREAD

**Issue by sugizo** [thombashi/youtube-wpm#2]
**env**
google colab

**steps**
```
pip install -U youtube-wpm  
!youtube-wpm https://youtu.be/QpBTM0GO6xI
```

**result**
```
Traceback (most recent call last):
  File "/usr/local/bin/youtube-wpm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/youtube_wpm/__main__.py", line 260, in main
    extract_outputs(
  File "/usr/local/lib/python3.10/dist-packages/youtube_wpm/__main__.py", line 124, in extract_outputs
    video_id: Final[str] = yt.vid_info["videoDetails"]["videoId"]
KeyError: 'videoDetails'
```

**execute**
`!youtube-wpm --format=md-table QpBTM0GO6xI qSkB8-zL3Mo`

**result**
```
Traceback (most recent call last):
  File "/usr/local/bin/youtube-wpm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/youtube_wpm/__main__.py", line 260, in main
    extract_outputs(
  File "/usr/local/lib/python3.10/dist-packages/youtube_wpm/__main__.py", line 124, in extract_outputs
    video_id: Final[str] = yt.vid_info["videoDetails"]["videoId"]
KeyError: 'videoDetails'
```

best regards

**Comment by thombashi** [comment]
@sugizo 
Thank you for your report.

Would you be able to provide more information on how to reproduce the problem? 
I could not reproduce the problem.
Command executions were succeeded when I executed at Google Colab.


```
!youtube-wpm --version
!youtube-wpm https://youtu.be/QpBTM0GO6xI
!youtube-wpm --format=md-table QpBTM0GO6xI qSkB8-zL3Mo
```

Results:

```
youtube-wpm 0.1.0
- Title: [Google I/O '23 in under 10 minutes](http://youtube.com/watch?v=QpBTM0GO6xI)
- Channel: [Google](https://www.youtube.com/channel/UCK8sQmJBp8GCxrOtXWBpyEA)
- Time: 9m 39s
- WPM: 173.5
- Auto Gen Transcript: False

|                                    Title                                     |                              Channel                               |  Time  |  WPM  | Auto Gen Transcript |
| ---------------------------------------------------------------------------- | ------------------------------------------------------------------ | ------ | ----: | ------------------- |
| [Google I/O '23 in under 10 minutes](http://youtube.com/watch?v=QpBTM0GO6xI) | [Google](https://www.youtube.com/channel/UCK8sQmJBp8GCxrOtXWBpyEA) | 9m 39s | 173.5 | False               |
| [Google Cloud \| Google I/O 2023](http://youtube.com/watch?v=qSkB8-zL3Mo)     | [Google](https://www.youtube.com/channel/UCK8sQmJBp8GCxrOtXWBpyEA) | 9m 27s | 161.0 | False               |
```

**Comment by sugizo** [comment]
fixed now, 
thank you
